version: '3.8'

services:
  threadfin:
    # Use existing pre-built image instead of building from source
    image: threadfinzane33:latest
    
    container_name: threadfin
    restart: unless-stopped
    
    # Use bridge networking for Docker Desktop compatibility
    # network_mode: host  # Disabled - doesn't work on Docker Desktop for Windows
    
    # Port mapping for bridge networking
    ports:
      - "34400:34400"           # HTTP API and streaming
      - "1900:1900/udp"         # SSDP/UPnP discovery
      # - "65002:65001/udp"     # HDHomeRun UDP discovery (if needed)
    
    volumes:
      - threadfin_conf:/home/threadfin/conf
      - threadfin_temp:/tmp/threadfin
      - threadfin_cache:/home/threadfin/cache
      - threadfin_logs:/var/log
    
    environment:
      - THREADFIN_PORT=34400
      - THREADFIN_BIND_IP_ADDRESS=0.0.0.0
      - THREADFIN_DEBUG=1             # Enable debug for troubleshooting
      - THREADFIN_BRANCH=main
      # - THREADFIN_DOMAIN=192.168.4.5:34400  # Remove fixed domain for Docker Desktop
      - THREADFIN_FAST_STARTUP=true  # Skip provider file updates for faster startup  
      - TZ=UTC                        # Use UTC for consistency
    
    # DNS configuration to resolve external hostnames
    dns:
      - 8.8.8.8          # Google DNS
      - 1.1.1.1          # Cloudflare DNS
      - 208.67.222.222   # OpenDNS
    
    # Optional: if you want to run as specific user/group
    # user: "31337:31337"
    
    # Optional: add labels for better organization in Portainer
    labels:
      - "traefik.enable=false"  # Disable if using Traefik
      - "com.centurylinklabs.watchtower.enable=true"  # Enable Watchtower updates
    
    # Optional: resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'

volumes:
  threadfin_conf:
    driver: local
  threadfin_temp:
    driver: local
  threadfin_cache:
    driver: local
  threadfin_logs:
    driver: local 