version: '3.8'

services:
  threadfin:
    # Option 1: Build from source (recommended for development)
    build:
      context: .
      dockerfile: Dockerfile
    # Option 2: Use pre-built image (uncomment if you have a built image)
    # image: threadfinzane33:latest
    
    container_name: threadfin
    restart: unless-stopped
    
    # Use host network mode for better SSDP/UPnP compatibility
    network_mode: host
    
    # Port mapping for bridge networking (disabled when using host mode)
    #ports:
    #  - "34400:34400"           # HTTP API and streaming
    #  - "1900:1900/udp"         # SSDP/UPnP discovery (mapped to avoid conflicts)
        #- "65002:65001/udp"       # HDHomeRun UDP discovery
    
    volumes:
      - threadfin_conf:/home/threadfin/conf
      - threadfin_temp:/tmp/threadfin
      - threadfin_cache:/home/threadfin/cache
      - threadfin_logs:/var/log
    
    environment:
      - THREADFIN_PORT=34400
      - THREADFIN_BIND_IP_ADDRESS=0.0.0.0
      - THREADFIN_DEBUG=0
      - THREADFIN_BRANCH=main
      - THREADFIN_DOMAIN=192.168.4.5:34400
      - THREADFIN_FAST_STARTUP=true  # Skip provider file updates for faster startup
      - TZ=Pacific/Auckland # Set your timezone
    
    # DNS configuration to resolve external hostnames
    dns:
      - 8.8.8.8          # Google DNS
      - 1.1.1.1          # Cloudflare DNS
      - 208.67.222.222   # OpenDNS
    
    # Optional: if you want to run as specific user/group
    # user: "31337:31337"
    
    # Optional: add labels for better organization in Portainer
    labels:
      - "traefik.enable=false"  # Disable if using Traefik
      - "com.centurylinklabs.watchtower.enable=true"  # Enable Watchtower updates
    
    # Optional: resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'

volumes:
  threadfin_conf:
    driver: local
  threadfin_temp:
    driver: local
  threadfin_cache:
    driver: local
  threadfin_logs:
    driver: local 