version: '3.8'

services:
  threadfin:
    image: threadfinzane33:latest
    container_name: threadfin
    restart: unless-stopped
    
    ports:
      - "34400:34400"
    
    volumes:
      - threadfin_conf:/home/threadfin/conf
      - threadfin_temp:/tmp/threadfin
      - threadfin_cache:/home/threadfin/cache
      - threadfin_logs:/var/log
    
    environment:
      - THREADFIN_PORT=34400
      - THREADFIN_BIND_IP_ADDRESS=0.0.0.0
      - THREADFIN_DEBUG=0
      - THREADFIN_BRANCH=main
      - TZ=Pacific/Auckland

volumes:
  threadfin_conf:
    driver: local
  threadfin_temp:
    driver: local
  threadfin_cache:
    driver: local
  threadfin_logs:
    driver: local 